### ISSUE TITLE
Server startup crash (NoSuchMethodError)

### ISSUE THREAD

**Issue by jburrows82** [KidsDontPlay/CWACOM#1]
http://pastebin.com/gi50gfSE

Have not tested this on vanilla Forge, or client side yet.

**Comment by jburrows82** [comment]
http://pastebin.com/DMu1wU58 vanilla Forge samething.

 @SideOnly?

**Comment by KidsDontPlay** [comment]
yes, its a bug I cannot fix.
i could make it not crashing, but then you have less fooditem at choice (only fooditems with metadata 0)

**Comment by jburrows82** [comment]
That's a shame.. I was looking forward to having fun with this mod on the server. Thank you for looking into the issue!

**Comment by KidsDontPlay** [comment]
there is a small chance I get it to work. maybe tomorrow

**Comment by KidsDontPlay** [comment]
solved
